### ISSUE TITLE
Searching for IOS taskwarrior client

### ISSUE THREAD

**Issue by kaihendry** [matt-snider/todoist-taskwarrior#3]
Can I assume you use Todoist on IOS and since to your local task warrior DB using https://github.com/matt-snider/todoist-taskwarrior/issues/1 ?

**Comment by matt-snider** [comment]
Hey Kai,

I am not using Todoist anymore. I developed this tool to migrate tasks out of Todoist into the local Taskwarrior DB. The tool referenced in #1 should do a two-way sync, if that's what you are looking for.
